name: Trigger auto deployment for dishaai

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/dishaai-AutoDeployTrigger-fa3a6a8f-86ae-4891-9797-e109a562a7e5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DISHAAI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DISHAAI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DISHAAI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}ritesh1729/my-streamlit-app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: hub.docker.com
          registryUsername: ${{ secrets.DISHAAI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DISHAAI_REGISTRY_PASSWORD }}
          containerAppName: dishaai
          resourceGroup: chatbot-rg
          imageToBuild: hub.docker.com/dishaai:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


