name: Deploy to Azure

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Build and push Docker image
      run: |
        docker build -t dishaai.azurecr.io/dishaai:${{ github.sha }} .
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login dishaai.azurecr.io -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
        docker push dishaai.azurecr.io/dishaai:${{ github.sha }}
    
    - name: Deploy to Container Apps
      uses: azure/container-apps-deploy-action@v2
      with:
        appSourcePath: ${{ github.workspace }}
        containerAppName: dishaai
        resourceGroup: chatbot-rg
        image: dishaai.azurecr.io/dishaai:${{ github.sha }}