name: Deploy to Azure

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/dishaai-AutoDeployTrigger-*.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DISHAAI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DISHAAI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DISHAAI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile  # Replace if it's in subfolder
          registryUrl: dishaai.azurecr.io
          registryUsername: ${{ secrets.DISHAAI_REGISTRY_USERNAME }}
          noCache: true
          registryPassword: ${{ secrets.DISHAAI_REGISTRY_PASSWORD }}
          containerAppName: dishaai
          resourceGroup: chatbot-rg
          imageToBuild: dishaai.azurecr.io/dishaai:${{ github.sha }}
